### ISSUE TITLE
allows replication without share persistent volumes

### ISSUE THREAD

**Issue by dottgonzo** [DanielDent/docker-postgres-replication#10]
Hi thanks for your code,
i'm looking for a solution that don't use persistent volumes. My goal is to be able to reinitializate the postgres data inside the master container, recovering them from a replica that is still alive, without the needs of share a common folder.I don't want to mount anything inside the container and be sure that if 1 replica stay up, all the data will be restored on master and the other replicas. Can you help me?

**Comment by DanielDent** [comment]
Automatic master failover, while achievable, is outside of the scope of project at this time. You may wish to look at some of the Kubernetes Postgres operators & high availability solutions.

If by common folder you mean NFS mount or other shared storage, this project will already do that - it simply doesn't have any automatic procedures for changing masters into slaves and vice/versa.
