### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by uLan08** [DanielDent/docker-postgres-replication#13]
Hi, I just want to know the current status of this project as the last commit is from more than a year ago. Would be a waste if this project ends up dying. And want to say that I am interested in helping to maintain this project. What would be the first steps to do so?

**Comment by DanielDent** [comment]
Thanks for the comment. Project is not dead, but I have not had any need to update it for a while. I'll take a look at clearing out tumbleweeds over the next bit.

I'm always happy to have contributions, and if you have anything specific you'd like to see or would like to contribute, please let me know.

**Comment by uLan08** [comment]
So the entrypoint right now is updated with the official postgres image?

**Comment by DanielDent** [comment]
I'll take a look at that in a few minutes here.

**Comment by DanielDent** [comment]
I've created a new patch based build process on the dev branch, and builds from this process temporarily live at https://hub.docker.com/r/danieldent/docker-postgres-replication-dev/ until I and other community members have had a chance to test these updates (the new build process also builds the -alpine variants as well as Postgres 10). I have not had time to even run these new builds, so please run this builds in test prior to dropping them into a production environment.
