### ISSUE TITLE
Deploy master and slave on different machines

### ISSUE THREAD

**Issue by pai911** [DanielDent/docker-postgres-replication#17]
I am not very familiar with docker-compose

But this sample looks like running master & slave on the same machine.

If I am right, is there a way to run them on two different machines?

**Comment by Hasdik** [comment]
@pai911, hi. It turned out to deploy master and slave on different machines?

**Comment by pai911** [comment]
> @pai911, hi. It turned out to deploy master and slave on different machines?

Hi! Sorry I haven't tried it yet.
I planned to try it in a few days, will get back to you :)

**Comment by Hasdik** [comment]
HI! But how can I contact you faster?

вт, 17 мар. 2020 г. в 13:39, John Bai <notifications@github.com>:

**Comment by DanielDent** [comment]
Historically I did this on Rancher 1.6. Something like swarm may be what you are looking for.
