### ISSUE TITLE
Data does not mount in local volume path

### ISSUE THREAD

**Issue by mostafakamal98** [DanielDent/docker-postgres-replication#5]
Awesome write up. Replication run fine in my side. Container data also works at '/var/lib/postgresql/data/pgdata'

Postgresql is installed in my local machine. But data dose not mount in below location

volumes:
     - '/var/lib/postgresql/data'

**Comment by DanielDent** [comment]
I'm not sure if I understand the issue. Are you familiar with how docker volumes work? If you are expecting to see the data outside of the docker volume (on a host path), the example docker-compose files will need to be modified.

**Comment by DanielDent** [comment]
Closing inactive issue.
